# Generated by Django 4.2.1 on 2023-06-07 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Contact_date',
            new_name='contact_date',
        ),
    ]
