# Generated by Django 4.2.1 on 2023-06-26 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_bathrooms_alter_listing_garage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='sqft',
            new_name='meter',
        ),
    ]
