# Generated by Django 4.2.4 on 2023-11-15 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_rename_sqft_listing_meter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='bedroom',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='garage',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='lot_size',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='meter',
        ),
    ]
