# Generated by Django 4.2.4 on 2023-11-15 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_remove_listing_bathrooms_remove_listing_bedroom_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='state',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='zipcode',
        ),
    ]
