# Generated by Django 4.2.4 on 2023-11-15 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_rename_title_listing_name_remove_listing_state_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='name',
            new_name='title',
        ),
    ]
